### ISSUE TITLE
Does not work on Meteor 1.2 release candidate

### ISSUE THREAD

**Issue by imkost** [arunoda/hello-react-meteor#5]
1. clone repo
2. meteor
3. everything runs like it should
4. meteor update --release METEOR@1.2-rc.12
5. application does not work

![image](https://cloud.githubusercontent.com/assets/2445890/9796001/7366e712-57fc-11e5-9ad7-a66acb46605e.png)

**Comment by arunoda** [comment]
I've updated packages for Meteor 1.2 and now it should work.
