### ISSUE TITLE
On code Change the whole app reloads

### ISSUE THREAD

**Issue by sahanDissanayake** [arunoda/hello-react-meteor#8]
Hi @arunoda ,

I thought react only redraw what's changed in the virtual DOM, but at the moment the the page refreshes, which takes away valuable developer time. Any thoughts ??

**Comment by sahanDissanayake** [comment]
CSS changes are instantly pushed to the browser without refresh, but not any other text or document tags changes

**Comment by arunoda** [comment]
Please ask these question in the Meteor Forums.
