### ISSUE TITLE
A minor concern with the way you have created files/code

### ISSUE THREAD

**Issue by sahanDissanayake** [arunoda/hello-react-meteor#9]
So at the moment the client sends the 'selector' to the server to subscribe to posts right ?
https://github.com/arunoda/hello-react-meteor/blob/master/both/components/post_list.jsx#L4

What if a bad user do this on their console, after checking out the code..

```
var handle = Meteor.subscribe('posts');
```

This will get all the posts no matter what right ?
Sorry, I see this as a issue. Please close if this is not an issue.

**Comment by sahanDissanayake** [comment]
yep.. Good stuff.. Keep up the good work :100:

**Comment by arunoda** [comment]
It has an issue because, we allow users to pass the selector to the subscription. That's something we can fix.

But exposing the source code to the pubic is not an issue. See Wordpress is open source.

**Comment by arunoda** [comment]
Check now.
